language: java
jdk: openjdk8
if: tag IS blank
before_install:
  - chmod +x buildscript.bash
install:
  - ./gradlew
script:
  - node buildscript.js
  - ./buildscript.bash
cache:
  directories:
    .gradle/
